meta_product_name: "Tribes"
meta_title: "Tribes - Coliving"
meta_description: "Tribes Coliving propose de magnifiques chambres où tout est inclus. Venez partager votre expérience avec des personnes qui vous ressemblent!"
meta_image: "opengraph.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
facebook_account: "@product_facebook_account"   # required for Twitter Cards
