meta_product_name: "Tribes"
meta_title: "Tribes - Coliving for inspired people"
meta_description: "Relevant description"
meta_image: "opengraphhome.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
facebook_account: "@product_facebook_account"   # required for Twitter Cards
